terraform {
  required_providers {
    civo = {
      source  = "civo/civo"
      version = "0.10.3"
    }
  }
}

variable "CIVO_TOKEN" {
  type = string
}

provider "civo" {
  token = var.CIVO_TOKEN
  region = "LON1"
}


resource "civo_network" "custom_net" {
    label = "ujjwal-home"
}

resource "civo_firewall" "www" {
  name = "www"
}

// resource "civo_firewall_rule" "http" {
//   firewall_id = civo_firewall.www.id
//   protocol = "tcp"
//   start_port = "8121"
//   end_port = "8121"
//   cidr = ["103.147.128.0/24"]
//   direction = "ingress"
//   label = "server web"
//   depends_on = [civo_firewall.www]
// }


resource "civo_firewall_rule" "ssh" {
  firewall_id = civo_firewall.www.id
  protocol    = "tcp"
  start_port  = "22"
  end_port    = "22"
  cidr        = ["103.147.128.0/24"]
  direction   = "ingress"
  label       = "server ssh"
  depends_on  = [civo_firewall.www]
}

// resource "civo_kubernetes_cluster" "cluster" {
//     name = "test"
//     region = "LON1"
//     applications = "Rancher"
//     num_target_nodes = 3
//     target_nodes_size = "g3.k3s.medium"
// }

// output "kubectl_config" {
//   description = "kubectl config as generated by the module."
//   value       = civo_kubernetes_cluster.kubeconfig
// }

// output "cluster_id" {
//   description = "Kubernetes cluster id"
//   value       = cluster.id
// }


// output "cluster_name" {
//   description = "Kubernetes cluster name"
//   value       = cluster.name
// }

// output "cluster_version" {
//   description = "Kubernetes cluster version"
//   value       = cluster.kubernetes_version
// }
